### ISSUE TITLE
Why can't I find the checkpiont file？

### ISSUE THREAD

**Issue by Vannaaaaa** [WilliamRo/EEG-Denoise#1]
Why can't I find the checkpiont file？

**Comment by SummerBae** [comment]
We apologize for not realizing earlier that the checkpoint file could not be uploaded to GitHub due to its large size. To address this issue, we have placed the checkpoint file in the G-node Database and updated the README.md file with information on how to access the checkpoint files. We hope this resolves your problem.

**Comment by zmy1260222041** [comment]
Hi SummerBae, I put the folder 'checkpoints' which include '0609_EOG_denoise' to '\EEG-Denoise\01-EEGDenoiseNet_Dataset' but can not successfully load the checkpoint file. I received the traceback:"OutOfRangeError: Read fewer bytes than requested" and other errors. I wonder if it is enough to put the folder in the directory? The whole message is like the following sentences: 


-> Start of MODNET_DENSE on EEG Signal task
--------------------------------------------------------------------------------
Model Choice-->> BaseNet+TPB+Dense
WARNING:tensorflow:From G:\Anaconda\envs\dtp-net\lib\site-packages\tensorflow_core\python\util\dispatch.py:180: calling squeeze (from tensorflow.python.ops.array_ops) with squeeze_dims is deprecated and will be removed in a future version.
Instructions for updating:
Use the `axis` argument instead
++ Optimizer defined in trainer hub is used.
>> Model built successfully:
.. Feedforward: input[?x1] => encoder(32x248)->relu => conv1d(1x64) => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => 
conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => mul
ti_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> 
conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(
4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) 
-> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConca
t => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) =
> multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrel
u -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> co
nv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x
394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concat
Concat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x
64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) ->
 lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu 
-> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv
1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_c
oncatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv
1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x39
4) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> l
relu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat => conv1d(1x394) -> lrelu -> conv1d(4x394) -> lrelu -> conv1d(1x64) => multi_concatConcat -> lrelu => conv1d(1x248) -> lrelu => decoder => output[Nonex1]
>> Launching session ...
2025-02-27 10:02:37.985776: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2025-02-27 10:02:37.999959: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2025-02-27 10:02:38.084890: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2025-02-27 10:02:38.112117: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: Laptop-MichaelZhong
2025-02-27 10:02:38.112556: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: Laptop-MichaelZhong
>> Session launched
>> Access to directory 'F:\EEG-Denoise\01-EEGDenoiseNet_Dataset\checkpoints\0609_EOG_denoise' ...
2025-02-27 10:02:40.327345: W tensorflow/core/framework/op_kernel.cc:1655] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Out of range: Read fewer bytes than requested
Traceback (most recent call last):
  File "G:\Anaconda\envs\dtp-net\lib\site-packages\tensorflow_core\python\client\session.py", line 1367, in _do_call
    return fn(*args)
  File "G:\Anaconda\envs\dtp-net\lib\site-packages\tensorflow_core\python\client\session.py", line 1352, in _run_fn
    target_list, run_metadata)
  File "G:\Anaconda\envs\dtp-net\lib\site-packages\tensorflow_core\python\client\session.py", line 1445, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read fewer bytes than requested
         [[{{node save/RestoreV2}}]]
